# Generated by Django 3.2.9 on 2021-11-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fomentoLectura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='observacion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
